name: Automate Data Preprocessing

# Akan aktif ketika ada push ke branch 'main'
on:
  push:
    branches:
      - main
    # Workflow ini berjalan hanya jika ada perubahan di folder raw data atau folder preprocessing
    paths:
      - dataset-kelayakan-beasiswa_raw/**'
      - 'preprocessing/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Mengambil kode dari repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Menyiapkan environment Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Menginstal library yang dibutuhkan
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy

      # 4. Menjalankan script automate
      - name: Run preprocessing script
        run: |
          python preprocessing/automate_RidhoAbdeeNugraha.py

      # 5. Menyimpan perubahan kembali ke repository GitHub (Commit & Push)
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add preprocessing/dataset-kelayakan-beasiswa_preprocessing/
          
          # Baris ini memastikan GitHub tidak error jika datanya ternyata tidak ada perubahan
          git diff --quiet && git diff --staged --quiet || git commit -m "Automated data preprocessing update via GitHub Actions"
          git push
